### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by rohapa** [siratama/PaletteChange#6]
Error installing on Mac OSX 10.10.2

![screen shot 2015-07-17 at 2 01 17 pm](https://cloud.githubusercontent.com/assets/11214062/8754905/5e0d375e-2c8c-11e5-820b-69c02234ba97.png)

**Comment by siratama** [comment]
When Adobe Extension Manager CC is reinstalled, there is a case that a extension can be installed.

**Comment by siratama** [comment]
I found solution a little. Update Extension Manager CC from Adobe Creative Cloud.
![update](https://cloud.githubusercontent.com/assets/3593619/8765823/3c40b512-2e5b-11e5-93a3-5f33c7723152.png)
Then zxp file can be installed.

But even if it's installed, PaletteChange panel doesn't appear. There seems to be a problem with Extension Manager CC. I'm looking for different solution method.

**Comment by siratama** [comment]
I found solution. Use the Extension Manager Command Line tool (ExManCmd).
https://www.adobeexchange.com/resources/28

**Comment by Archeia** [comment]
It works for me when I use the CMD command :D
